-
    hosts: localhost
    vars_files:
        - external_vars.yaml
    vars:
        db_password: "{{ lookup('password', 'db.password') }}"
        gcloud_creds_text: "{{ lookup('pipe', 'gcloud config config-helper --format=json') }}"
        gcloud_credentials: "{{ gcloud_creds_text | json_query('@') }}"
    tags: create
    tasks:
        -
            name: Gather cluster facts
            gcp_container_cluster_facts:
                project: "{{ gcp_project_id }}"
                auth_kind: serviceaccount
                service_account_file: "{{ gcp_cred_file }}"
                zone: "{{gcp_zone }}"
            register: clusters
        -
            set_fact:
                cluster: "{{ clusters['items'] | selectattr('name', 'match', cluster_name) | first  }}"
        -
            name: Create a MariaDB deployment
            k8s:
                host: "https://{{ cluster.endpoint }}"
                ca_cert: "{{ cluster.masterAuth.clusterCaCertificate }}"
                #validate_certs: false
                api_key: "{{ gcloud_credentials.credential.access_token }}"
                namespace: "default"
                definition:
                    apiVersion: apps/v1
                    kind: Deployment
                    metadata:
                        name: mariadb-server
                    spec:
                        replicas: 1
                        selector:
                            matchLabels:
                                app: mariadb
                                role: master
                                tier: backend
                        template:
                            metadata:
                                labels:
                                    app: mariadb
                                    role: master
                                    tier: backend
                            spec:
                                containers:
                                    -
                                        # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#container-v1-core
                                        name: db
                                        image: mariadb/server
                                        env:
                                            -
                                                name: "MARIADB_ROOT_PASSWORD"
                                                value: "{{ db_password }}"
                                        resources:
                                            requests:
                                                cpu: 100m
                                                memory: 100Mi
                                        ports:
                                            -
                                                containerPort: 3306
                                        volumeMounts:
                                            -
                                                mountPath: /var/lib/mysql
                                                name: db-volume
                                volumes:
                                    -
                                        name: db-volume
                                        gcePersistentDisk:
                                            pdName: lb-demo-db
                                            fsType: ext3

# vim: set sw=4 ts=4 et indk= :
