apiVersion: apps/v1
kind: Deployment
metadata:
    name: mariadb-server
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mariadb
            role: master
            tier: backend
    template:
        metadata:
            labels:
                app: mariadb
                role: master
                tier: backend
        spec:
            containers:
                -
                    # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#container-v1-core
                    name: db
                    image: mariadb/server
                    env:
                        -
                            name: "MARIADB_RANDOM_ROOT_PASSWORD"
                            value: "yes"
                    resources:
                        requests:
                            cpu: 100m
                            memory: 100Mi
                    ports:
                        -
                            containerPort: 3306
                    volumeMounts:
                        -
                            mountPath: /var/lib/mysql
                            name: db-volume
            volumes:
                -
                    name: db-volume
                    gcePersistentDisk:
                        pdName: lb-demo-db
                        fsType: ext3

# vim: set sw=4 ts=4 et indk= :
